on:
  schedule:
    - cron: "30 5 * * *"
  push:
jobs:
  interop:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    strategy:
      fail-fast: false
      matrix:
        browser: ['chrome']
        bver: ['stable', 'beta', 'unstable']
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-node@v3
    - run: npm install
    - run: BROWSER=${{matrix.browser}} BVER=${{matrix.bver}} ./node_modules/travis-multirunner/setup.sh
    - run: Xvfb :99 &
    - name: interop
      run: BROWSER=${{matrix.browser}} BVER=${{matrix.bver}} DISPLAY=:99.0 node_modules/.bin/karma start test/karma.conf.js
